#! /bin/bash
## ETJAKEOC YouTube Downloader Script

export PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:$PATH # Make sure that 'PATH' is proper.

## We set all the variables for 'yt-dlp'
## We then create our new variable for the script to append a couple more options.

LOG="/MEDIA/dlp_yt_log.txt" # Log location
yt="/YOUTUBE" # Where the YouTube main directory is.
yts="/home/YT-DLS" # Where the YouTube script directory is.
yturl="https://www.youtube.com" # A variable designed to make the script below a little neater.
# Set our flags for pulling videos how we like.
defflags=(
 -N 2
 --extractor-args "youtubepot-bgutilhttp:base_url=http://127.0.0.1:4416"
 -f "bv*[height<=1080][fps<=60]+ba/bestvideo+bestaudio/best"
 -S vcodec:h264,res:1080,fps:60,acodec:aac
 --cookies /MEDIA/yt-dlp-cookies.txt
 --download-archive /MEDIA/IDs.db
 --hls-prefer-native
 --mtime
 --no-overwrites
 --no-post-overwrites
 --playlist-end 1
 --sponsorblock-mark all
 --sponsorblock-remove sponsor,selfpromo
 --sub-lang "en.*,en,de,pl"
 --sub-format "vtt/srt"
 --write-info-json
 --write-thumbnail
 --write-subs
 --write-auto-subs
)
dlp_yt=(nice -n 5 yt-dlp "${defflags[@]}") # 'dlp_yt' variable that imports all of our settings for ease of use below.

## Echo out the flags to the log, to ensure they are being sourced.
## We nuke the old log, and rewrite it from scratch from this point.
echo "YouTube download script started at:" $(date) > $LOG
echo -e "Echoing applied variables into dlp_yt_log.txt:" >> $LOG
echo -e "yt: $yt" >> $LOG
echo -e "yts: $yts" >> $LOG
echo -e "defflags: ${defflags[@]}" >> $LOG
echo -e "dlp_yt command: ${dlp_yt[@]}" >> $LOG

## Change into the YouTube directory, then the channel directory, and begins downloading with our defined flags.
cd $yt/Applied\ Science/ && "${dlp_yt[@]}" $yturl/@AppliedScience/videos &
cd $yt/Atomic\ Frontier/ && "${dlp_yt[@]}" $yturl/@AtomicFrontier/videos &
cd $yt/Asianometry/ && "${dlp_yt[@]}" $yturl/@Asianometry/videos &
cd $yt/AW/ && "${dlp_yt[@]}" $yturl/@agingwheels/videos &
cd $yt/Big\ Clive/ && "${dlp_yt[@]}" $yturl/@bigclivedotcom/videos &
cd $yt/BR/ && "${dlp_yt[@]}" $yturl/@BrodieRobertson/videos &
cd $yt/CI/ && "${dlp_yt[@]}" $yturl/c/CertifiablyIngame/videos &
cd $yt/Code\ Bullet/ && "${dlp_yt[@]}" $yturl/@CodeBullet/videos
cd $yt/Codyslab/ && "${dlp_yt[@]}" $yturl/@theCodyReeder/videos &
cd $yt/DDT/ && "${dlp_yt[@]}" $yturl/@DawidDoesTechStuff/videos &
cd $yt/EA/ && "${dlp_yt[@]}" $yturl/@electrarc240/videos &
cd $yt/EE/ && "${dlp_yt[@]}" $yturl/@EngineeringExplained/videos &
cd $yt/EMPLemon/ && "${dlp_yt[@]}" $yturl/@EmperorLemon/videos &
cd $yt/Garbage\ Time/ && "${dlp_yt[@]}" $yturl/@GarbageTime420/videos &
cd $yt/G54/ && "${dlp_yt[@]}" $yturl/@Garage54ENG/videos &
cd $yt/IGP/ && "${dlp_yt[@]}" $yturl/@IGP/videos
cd $yt/Knowledgia/ && "${dlp_yt[@]}" $yturl/@Knowledgia/videos &
cd $yt/Kurzgesagt/ && "${dlp_yt[@]}" $yturl/@kurzgesagt/videos &
cd $yt/MB/ && "${dlp_yt[@]}" $yturl/@MrBallen/videos &
cd $yt/MegaBuilds/ && "${dlp_yt[@]}" $yturl/@MegaBuildsYT/videos &
cd $yt/MF/ && "${dlp_yt[@]}" $yturl/@UndecidedMF/videos &
cd $yt/MH/ && "${dlp_yt[@]}" $yturl/@MajorHardware/videos &
cd $yt/Nexpo/ && "${dlp_yt[@]}" $yturl/@Nexpo/videos &
cd $yt/Night\ Mind/ && "${dlp_yt[@]}" $yturl/@NightMind/videos
cd $yt/NileBlue/ && "${dlp_yt[@]}" $yturl/@NileBlue/videos &
cd $yt/NileRed/ && "${dlp_yt[@]}" $yturl/@NileRed/videos &
cd $yt/PBSST/ && "${dlp_yt[@]}" $yturl/@pbsspacetime/videos &
cd $yt/PE/ && "${dlp_yt[@]}" $yturl/c/@PracticalEngineeringChannel/videos &
cd $yt/PF/ && "${dlp_yt[@]}" $yturl/c/@ProjectFarm/videos &
cd $yt/Qxir/ && "${dlp_yt[@]}" $yturl/c/QxirYT/videos &
cd $yt/RB/ && "${dlp_yt[@]}" $yturl/@RetroBytesUK/videos &
cd $yt/SH/ && "${dlp_yt[@]}" $yturl/c/@SabineHossenfelder/videos
cd $yt/Steve\ Hofstetter/ && "${dlp_yt[@]}" $yturl/c/@stevehofstetter/videos &
cd $yt/Scar/ && "${dlp_yt[@]}" $yturl/c/@GoodTimesWithScar/videos &
cd $yt/SEA/ && "${dlp_yt[@]}" $yturl/@SEA/videos &
cd $yt/SOG/ && "${dlp_yt[@]}" $yturl/@SomeOrdinaryGamers/videos &
cd $yt/SP/ && "${dlp_yt[@]}" $yturl/c/@styropyro/videos &
cd $yt/SW/ && "${dlp_yt[@]}" $yturl/c/@silentwisperer/videos &
cd $yt/SZS/ && "${dlp_yt[@]}" $yturl/c/@SubjectZeroScience/videos &
cd $yt/The\ Backyard\ Scientist/ && "${dlp_yt[@]}" $yturl/@TheBackyardScientist/videos &
cd $yt/The\ Thought\ Emporium/ && "${dlp_yt[@]}" $yturl/@thethoughtemporium/videos
cd $yt/TC/ && "${dlp_yt[@]}" $yturl/c/@TechnologyConnections/videos &
cd $yt/TE/ && "${dlp_yt[@]}" $yturl/@TechnologyConnextras/videos &
cd $yt/TSP/ && "${dlp_yt[@]}" $yturl/@theserialport/videos &
cd $yt/VZ/ && "${dlp_yt[@]}" $yturl/@coffeezillaextras/videos &
cd $yt/WarpedPerception/ && "${dlp_yt[@]}" $yturl/@WarpedYT/videos &
cd $yt/Wendigoon/ && "${dlp_yt[@]}" $yturl/@Wendigoon/videos

## Longer videos broken out to the end
cd $yt/Tech\ Ingredients/ && "${dlp_yt[@]}" $yturl/c/TechIngredients/videos
cd $yt/TWF/ && "${dlp_yt[@]}" $yturl/@TheWhyFiles/videos
cd $yt/EF/ && "${dlp_yt[@]}" $yturl/@ExplosionsAndFire/videos
cd $yt/EI/ && "${dlp_yt[@]}" $yturl/@ExtractionsAndIre/videos
cd $yt/CRD/ && "${dlp_yt[@]}" $yturl/c/@CathodeRayDude/videos
cd $yt/Veritasium/ && "${dlp_yt[@]}" $yturl/@veritasium/videos &

## Do some basic cleanup of the dirs
wait
sleep 60
$yts/CLEANUP.sh
$yts/PERMS.sh
#$yts/COV.sh

## Change back into the main YouTube directory, and echos a timestamp into a log file, telling us how long the script ran for.
echo "YouTube download script completed at:" $(date) >> $LOG
