sudo chown -R jake:plex /MEDIA
sudo chmod -R u+rwx /MEDIA
sudo chmod -R g+rwx /MEDIA
sudo chmod -R o-rw /MEDIA
sudo chmod -R o+x /MEDIA
sudo chown -R jake:plex /STORAGE/YOUTUBE
sudo chmod -R u+rwx /STORAGE/YOUTUBE
sudo chmod -R g+rwx /STORAGE/YOUTUBE
sudo chmod -R o-rw /STORAGE/YOUTUBE
sudo chmod -R o+x /STORAGE/YOUTUBE
