-4
-N 16
--part
-r 250M
--mtime
--continue
--downloader aria2c
--downloader-args '-c -j 16 -x 16 -s 16 -k 1M'
--http-chunk-size 10M
--no-overwrites
--embed-metadata
--embed-thumbnail
--embed-chapters
--embed-info-json
--embed-subs
--sub-lang en
--sub-format=best
-S +res:1080,+codec:vp9:opus
--merge-output-format mkv
