-4
--part
-r 500M
--downloader aria2c
--downloader-args '-c -j 16 -x 16 -s 16 -k 1M'
--no-overwrites
--embed-metadata
--embed-thumbnail
--embed-chapters
--embed-subs
--sub-lang en
--convert-subs=srt
-S +res:1080,+codec:vp9:aac
--merge-output-format mkv

#down="-4 -r 500M --video-multistreams --audio-multistreams" # Set the downloader flags.
