-N 8
--part
-r 250M
--mtime
--continue
--downloader aria2c
--downloader-args '-c -j 8 -x 8 -s 8 -k 2M'
--http-chunk-size 32M
--no-overwrites
--embed-thumbnail
--embed-chapters
--embed-subs
--sponsorblock-remove sponsor
--sub-lang en
--sub-format=best
-S +res:1080,+fps:60,+ext:mkv,+codec:(vp9|h264),+acodec:(aac|flac|mp3|ogg|ac3)
--merge-output-format mkv
